apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  annotations:
{{- with .Values.service.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.ports.http }}
      targetPort: {{ .Values.ports.http }}
    - name: https
      port: {{ .Values.ports.https }}
      targetPort: {{ .Values.ports.https }}
    - name: bridge-v1
      port: {{ .Values.ports.bridgeV1 }}
      targetPort: {{ .Values.ports.bridgeV1 }}
    - name: bridge-v2
      port: {{ .Values.ports.bridgeV2 }}
      targetPort: {{ .Values.ports.bridgeV2 }}